Course.find_or_create_by(id: 1, name: "Basic vocabulary", image: "1.jpeg")
Course.find_or_create_by(id: 2, name: "Basic pronunciation", image: "2.jpeg")
Course.find_or_create_by(id: 3, name: "IELTS Reading Basics", image: "3.jpeg")
Course.find_or_create_by(id: 4, name: "IELTS Listening Basics", image: "4.jpeg")
Course.find_or_create_by(id: 5, name: "IELTS Speaking Basics", image: "5.jpeg")
Course.find_or_create_by(id: 6, name: "IELTS Writing Basics", image: "6.jpeg")